services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main_flask.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
